apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: another-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/glichtenISP/back-stack
    path: /demo/applications/
    targetRevision: HEAD
  destination: 
    name: hostcluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
