apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-cluster-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: demo/clusters
    repoURL: https://github.com/glichtenISP/kubecon-demo-2023
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
